#pragma once

#include <Arduino.h>
#include <Wire.h>

#if defined(ARDUINO_ARCH_AVR)
#include <avr/pgmspace.h>
#endif

class AMT630A_OSD {
public:
  static constexpr uint8_t WINDOW_COUNT = 5;
  static constexpr uint16_t INDEX_RAM_CELLS = 512;
  static constexpr uint16_t FONT_RAM_WORDS = 4096;
  static constexpr uint8_t CUSTOM_GLYPH_ROWS = 16;
  static constexpr uint16_t MAX_CUSTOM_GLYPHS = 184;
  static constexpr uint8_t BITMAP_PALETTE_SIZE = 16;
  static constexpr uint8_t MAX_BITMAPS = 16;
  static constexpr uint16_t CUSTOM_RAM_GLYPH_BASE = 0x1C0;

  enum FontMode : uint8_t {
    LargeFont = 0,
    SmallFont = 1
  };

  enum WindowMode : uint8_t {
    TextMode = 0,
    BitmapMode = 1
  };

  enum Color : uint8_t {
    Transparent = 0,
    White       = 1,
    Red         = 2,
    Green       = 3,
    Blue        = 4,
    Cyan        = 5,
    Yellow      = 6,
    Black       = 7
  };

  enum Error : uint8_t {
    NoError = 0,
    NotBegun,
    InvalidWindow,
    WindowNotConfigured,
    WindowsAlreadyConfigured,
    InvalidDimensions,
    IndexRAMFull,
    InvalidGlyph,
    InvalidGlyphSlot,
    CustomGlyphUnsupportedInSmallFont,
    WrongWindowMode,
    FontRAMFull,
    BitmapMemoryFull,
    InvalidBitmap,
    InvalidBitmapHandle,
    BitmapSlotsFull,
    BitmapGeometryMismatch,
    BitmapUnsupportedInSmallFont,
    BitmapInUse,
    CustomGlyphBitmapConflict,
    InvalidPaletteIndex,
    InvalidOpacity,
    InvalidBrightness,
    InvalidScale,
    I2CError,
    AllocationFailed,
    FactoryMenuNotConfigured,
    FactoryMenuSequenceTooLong
  };

  // Generated by the companion Python converter. Data is 4bpp packed as four
  // palette indexes per 16-bit Font RAM word. Pixel order is left-to-right
  // from the high nibble to the low nibble: P0<<12 | P1<<8 | P2<<4 | P3.
  // Palette entries use AMT's nominal 12-bit BBBB GGGG RRRR layout.
  struct Bitmap {
    uint16_t width;
    uint16_t height;
    uint8_t tileWidth;
    uint8_t tileHeight;
    uint8_t columns;
    uint8_t rows;
    uint16_t wordCount;
    uint8_t paletteSize;
    bool palette0Transparent;
    const uint16_t *palette;
    const uint16_t *data;
  };

  using BitmapHandle = int8_t;
  static constexpr BitmapHandle INVALID_BITMAP_HANDLE = -1;

  AMT630A_OSD();
  ~AMT630A_OSD();

  bool begin(int sdaPin = 21, int sclPin = 22, uint32_t i2cClock = 100000);

  // Optional factory-menu keypad automation. This is intended for AMT630A
  // products whose stock firmware exposes a useful factory/service mode.
  // It is hardware/firmware specific and is never invoked automatically.
  enum FactoryButton : uint8_t {
    FactoryMenu = 0,
    FactoryPlus = 1,
    FactoryMinus = 2
  };

  struct FactoryMenuStep {
    FactoryButton button;
    uint16_t delayAfterMs;  // 0 = use configured default gap
  };

  static constexpr uint8_t MAX_FACTORY_MENU_STEPS = 32;

  bool configureFactoryMenuControl(uint8_t menuPin, uint8_t plusPin, uint8_t minusPin);
  bool setFactoryMenuTiming(uint16_t pressTimeMs, uint16_t gapTimeMs);
  bool setFactoryMenuSequence(const FactoryMenuStep *steps, uint8_t count);
  void useDefaultFactoryMenuSequence();
  bool enterFactoryMode();

  bool setDisplaySize(uint16_t width, uint16_t height);
  bool setFontMode(FontMode fontMode);
  FontMode getFontMode() const { return _fontMode; }
  uint16_t getDisplayWidth() const { return _displayWidth; }
  uint16_t getDisplayHeight() const { return _displayHeight; }

  // Text window configuration. Bitmap windows should normally be created with
  // configureBitmapWindow(), which derives the tile grid from a loaded bitmap.
  bool configureWindow(uint8_t windowNumber, uint16_t width, uint16_t height,
                       WindowMode mode = TextMode);
  bool configureBitmapWindow(uint8_t windowNumber, BitmapHandle bitmapHandle);
  bool releaseWindow(uint8_t windowNumber);
  bool isWindowConfigured(uint8_t windowNumber) const;
  WindowMode getWindowMode(uint8_t windowNumber) const;
  BitmapHandle getWindowBitmap(uint8_t windowNumber) const;

  bool setDisplayOrigin(uint8_t windowNumber, uint16_t x, uint16_t y);

  // Batch multiple hardware updates into one C6 unlock/relock window. Calls
  // may be nested; only the outermost begin/end pair touches C6. Existing
  // register-writing methods automatically participate because the low-level
  // unlockFast()/relockFast() helpers become no-ops while a batch is active.
  bool beginBatchUpdate();
  bool endBatchUpdate();
  bool isBatchUpdateActive() const { return _batchDepth > 0; }

  // Lightweight position update for animation. Unlike setDisplayOrigin(), this
  // changes only the hardware position register bytes that actually changed;
  // it does not rewrite window size or Index RAM configuration.
  bool moveWindow(uint8_t windowNumber, uint16_t x, uint16_t y);
  uint16_t getWindowX(uint8_t windowNumber) const;
  uint16_t getWindowY(uint8_t windowNumber) const;
  uint16_t getWindowWidth(uint8_t windowNumber) const;
  uint16_t getWindowHeight(uint8_t windowNumber) const;
  uint8_t getColumns(uint8_t windowNumber) const;
  uint8_t getRows(uint8_t windowNumber) const;
  uint8_t getCharacterWidth(uint8_t windowNumber) const;
  uint8_t getCharacterHeight(uint8_t windowNumber) const;
  uint16_t getWindowIndexStart(uint8_t windowNumber) const;
  uint16_t getWindowIndexCells(uint8_t windowNumber) const;
  uint16_t getIndexRAMUsed() const;
  uint16_t getIndexRAMFree() const { return INDEX_RAM_CELLS - getIndexRAMUsed(); }

  bool clearWindow(uint8_t windowNumber);
  bool clearRegion(uint8_t windowNumber, uint8_t x, uint8_t y,
                   uint8_t width, uint8_t height);
  bool fillRect(uint8_t windowNumber, uint8_t x, uint8_t y,
                uint8_t width, uint8_t height, Color background);
  bool setCell(uint8_t windowNumber, uint8_t x, uint8_t y, uint16_t glyph,
               Color foreground = White, Color background = Transparent);
  bool writeGlyph(uint8_t windowNumber, uint8_t x, uint8_t y, uint16_t glyph,
                  Color foreground = White, Color background = Transparent);
  size_t writeString(uint8_t windowNumber, uint8_t x, uint8_t y, const char *text,
                     Color foreground = White, Color background = Transparent);
  size_t writeString(uint8_t windowNumber, uint8_t x, uint8_t y, const String &text,
                     Color foreground = White, Color background = Transparent);
  size_t writeStringCentered(uint8_t windowNumber, uint8_t y, const char *text,
                             Color foreground = White, Color background = Transparent);
  size_t writeStringCentered(uint8_t windowNumber, uint8_t y, const String &text,
                             Color foreground = White, Color background = Transparent);
  uint16_t getTextWidth(uint8_t windowNumber, const char *text) const;
  size_t writeBar(uint8_t windowNumber, uint8_t x, uint8_t y,
                  uint16_t value, uint16_t maxValue, uint8_t width,
                  Color foreground = White, Color background = Transparent);

  // Font RAM partition. 0 reserves no custom-glyph slots and makes the entire
  // 4096-word Font RAM available to bitmaps. A nonzero reservation remains
  // unavailable to the bitmap allocator even before glyphs are loaded.
  bool configureFontRAM(uint16_t customGlyphCount);
  uint16_t getCustomGlyphCapacity() const { return _customGlyphCapacity; }
  uint16_t getCustomGlyphCount() const { return _customGlyphLoadedCount; }
  uint16_t getBitmapMemoryTotal() const { return _bitmapWordsTotal; }
  uint16_t getBitmapMemoryUsed() const { return _bitmapWordsUsed; }
  uint16_t getBitmapMemoryFree() const { return _bitmapWordsTotal - _bitmapWordsUsed; }
  uint32_t getBitmapMemoryTotalBytes() const { return (uint32_t)_bitmapWordsTotal * 2U; }
  uint32_t getBitmapMemoryUsedBytes() const { return (uint32_t)_bitmapWordsUsed * 2U; }
  uint32_t getBitmapMemoryFreeBytes() const { return (uint32_t)getBitmapMemoryFree() * 2U; }

  bool loadCustomGlyph(uint16_t slot, const uint16_t rows[CUSTOM_GLYPH_ROWS]);
  uint16_t getCustomGlyphId(uint16_t slot) const;
  bool writeCustomGlyph(uint8_t windowNumber, uint8_t x, uint8_t y, uint16_t slot,
                        Color foreground = White, Color background = Transparent);

  // Bitmap resources. v0.5.1 intentionally supports LargeFont geometry only
  // (16x22 tiles), allowing bitmap windows to coexist with ROM-font text
  // windows without changing the global FB76/FB77 geometry.
  bool loadBitmap(const Bitmap &bitmap, BitmapHandle &handle, bool applyPalette = true);
  bool clearBitmaps();
  uint8_t getBitmapCount() const { return _bitmapCount; }
  bool isBitmapLoaded(BitmapHandle handle) const;
  uint16_t getBitmapWidth(BitmapHandle handle) const;
  uint16_t getBitmapHeight(BitmapHandle handle) const;
  uint16_t getBitmapStorageBytes(BitmapHandle handle) const;

  // One global 16-entry hardware bitmap palette is shared by all bitmap windows.
  // RGB helpers accept normal 0..255 components and quantize each to four bits.
  bool setBitmapPaletteColor(uint8_t index, uint8_t red, uint8_t green, uint8_t blue);
  bool setBitmapPaletteColorRaw(uint8_t index, uint16_t bgr12);
  uint16_t getBitmapPaletteColorRaw(uint8_t index) const;
  bool applyBitmapPalette(const Bitmap &bitmap);
  bool setBitmapPalette0Transparent(bool transparent);
  bool isBitmapPalette0Transparent() const { return _bitmapPalette0Transparent; }
  static uint16_t rgbToBitmapColor(uint8_t red, uint8_t green, uint8_t blue);

  // Global OSD/video blending. These controls apply to all five hardware
  // OSD windows together. Hardware testing established opacity 0 as fully
  // transparent and opacity 7 as maximum OSD opacity. Enabling blending uses
  // the verified whole-OSD blend mode.
  bool setBlendingEnabled(bool enabled);
  bool isBlendingEnabled() const { return _blendingEnabled; }
  bool setOpacity(uint8_t opacity);
  uint8_t getOpacity() const { return _opacity; }
  bool setBrightness(uint8_t brightness);
  uint8_t getBrightness() const { return _brightness; }

  // Per-window character/tile scaling. A unified 1x..4x API is exposed for
  // all five windows even though AMT630A Window 0 uses different scaler
  // hardware internally. Horizontal and vertical scale may be set together
  // or independently. Scaling applies equally to text and bitmap windows.
  bool setWindowScale(uint8_t windowNumber, uint8_t scale);
  bool setWindowScale(uint8_t windowNumber, uint8_t scaleX, uint8_t scaleY);
  uint8_t getWindowScaleX(uint8_t windowNumber) const;
  uint8_t getWindowScaleY(uint8_t windowNumber) const;

  // Hardware blink support. The AMT630A exposes one verified primary blink
  // engine that can target one OSD window at a time. Region coordinates are
  // 1-based character/tile cells: the first cell is (1,1). Smaller raw rate values
  // blink faster; the exact time mapping is hardware-dependent and has not
  // been calibrated.
  bool configureBlink(uint8_t windowNumber, uint8_t x, uint8_t y,
                      uint8_t width, uint8_t height, uint8_t rawRate);
  bool setBlinkWindow(uint8_t windowNumber);
  bool setBlinkRegion(uint8_t x, uint8_t y, uint8_t width, uint8_t height);
  bool setBlinkRateRaw(uint8_t rawRate);
  bool setBlinkEnabled(bool enabled);
  uint8_t getBlinkWindow() const { return _blinkWindow; }
  uint8_t getBlinkX() const { return _blinkX; }
  uint8_t getBlinkY() const { return _blinkY; }
  uint8_t getBlinkWidth() const { return _blinkWidth; }
  uint8_t getBlinkHeight() const { return _blinkHeight; }
  uint8_t getBlinkRateRaw() const { return _blinkRateRaw; }
  bool isBlinkEnabled() const { return _blinkEnabled; }

  bool updateDisplay();
  bool updateDisplay(uint8_t windowNumber);
  bool forceUpdate();
  bool forceUpdate(uint8_t windowNumber);

  void setOSDVisible(bool visible);
  bool isOSDVisible() const { return _osdVisible; }
  bool setVisible(uint8_t windowNumber, bool visible);
  bool isVisible(uint8_t windowNumber) const;

  void service();
  void setServiceInterval(uint16_t milliseconds) { _serviceIntervalMs = milliseconds; }

  void setFactoryOSDCoexistence(bool enabled);
  bool getFactoryOSDCoexistence() const { return _factoryOSDCoexistence; }

  Error getLastError() const { return _lastError; }
  void clearError() { _lastError = NoError; }
  static const char *errorToString(Error error);

private:
  struct Cell {
    uint16_t glyph;
    uint8_t attr;
    bool dirty;
  };

  struct WindowState {
    bool configured;
    bool visible;
    WindowMode mode;
    BitmapHandle bitmapHandle;
    uint16_t width;
    uint16_t height;
    uint16_t x;
    uint16_t y;
    uint8_t scaleX;
    uint8_t scaleY;
    uint8_t columns;
    uint8_t rows;
    uint16_t indexStart;
    uint16_t cellCount;
    Cell *cells;
  };

  struct BitmapResource {
    bool loaded;
    uint16_t width;
    uint16_t height;
    uint8_t tileWidth;
    uint8_t tileHeight;
    uint8_t columns;
    uint8_t rows;
    uint8_t wordsPerRow;
    uint16_t wordCount;
    uint16_t startWord;
    uint16_t startTile;
    uint16_t firstGlyph;
  };

  static constexpr uint8_t DEV_OSD = 0x5B;
  static constexpr uint8_t DEV_SYS = 0x5F;

  static constexpr uint16_t LARGE_CUSTOM_GLYPH_BASE = 0x336;
  static constexpr uint16_t LARGE_CUSTOM_FONT_RAM_BASE = 0x024;
  static constexpr uint8_t LARGE_CUSTOM_GLYPH_STRIDE = 22;

  TwoWire *_wire;
  bool _begun;
  bool _osdVisible;
  bool _factoryOSDCoexistence;
  uint8_t _originalC6;
  uint16_t _batchDepth;
  uint8_t _blinkWindow;
  uint8_t _blinkX;
  uint8_t _blinkY;
  uint8_t _blinkWidth;
  uint8_t _blinkHeight;
  uint8_t _blinkRateRaw;
  bool _blinkEnabled;
  bool _blinkManaged;
  bool _blendingEnabled;
  uint8_t _opacity;
  uint8_t _brightness;
  FontMode _fontMode;
  uint16_t _displayWidth;
  uint16_t _displayHeight;
  WindowState _windows[WINDOW_COUNT];

  uint16_t _customGlyphCapacity;
  uint16_t _customGlyphLoadedCount;
  bool _customGlyphLoaded[MAX_CUSTOM_GLYPHS];

  uint16_t _bitmapStartWord;
  uint16_t _bitmapWordsTotal;
  uint16_t _bitmapWordsUsed;
  uint16_t _bitmapNextWord;
  uint16_t _bitmapStartTile;
  bool _bitmapStartConfigured;
  uint8_t _bitmapCount;
  BitmapResource _bitmaps[MAX_BITMAPS];
  uint16_t _bitmapPalette[BITMAP_PALETTE_SIZE];
  bool _bitmapPalette0Transparent;

  uint8_t _factoryMenuPin;
  uint8_t _factoryPlusPin;
  uint8_t _factoryMinusPin;
  bool _factoryMenuControlConfigured;
  uint16_t _factoryPressTimeMs;
  uint16_t _factoryGapTimeMs;
  FactoryMenuStep _factoryMenuSequence[MAX_FACTORY_MENU_STEPS];
  uint8_t _factoryMenuSequenceCount;

  uint16_t _serviceIntervalMs;
  unsigned long _lastServiceMs;
  Error _lastError;

  bool fail(Error error);
  bool validWindow(uint8_t windowNumber) const;
  bool validBitmapHandle(BitmapHandle handle) const;
  bool anyWindowConfigured() const;
  bool anyBitmapWindowConfigured() const;
  bool anyBitmapWindowVisible() const;
  void characterGeometry(uint8_t &width, uint8_t &height) const;
  uint16_t alignUp(uint16_t value, uint16_t alignment) const;

  uint8_t readReg(uint8_t dev, uint8_t reg);
  bool writeReg(uint8_t dev, uint8_t reg, uint8_t value);
  void unlockFast();
  void relockFast();
  uint8_t readOSDReg(uint8_t reg);
  bool writeOSDConservative(uint8_t reg, uint8_t value);

  bool configureGlobalHardware();
  bool configureWindowHardware(uint8_t windowNumber);
  bool configureAllWindowsHardware();
  bool configureBitmapStartHardware();
  bool applyWindowScaleHardware(uint8_t windowNumber);
  bool applyBlinkHardware();
  bool applyVisibility();

  bool configureWindowCells(uint8_t windowNumber, uint16_t width, uint16_t height,
                            uint8_t columns, uint8_t rows, WindowMode mode,
                            BitmapHandle bitmapHandle);
  bool allocateWindowBuffer(uint8_t windowNumber, uint16_t count);
  void freeWindowBuffer(uint8_t windowNumber);
  bool reallocateIndexRAM();
  void markAllDirty(uint8_t windowNumber);

  void setIndexAddress(uint16_t addr);
  bool writeFontRamWord(uint16_t address, uint16_t data);
  bool writeFontRamBlock(uint16_t startAddress, const uint16_t *data, uint16_t wordCount);
  bool flushWindow(uint8_t windowNumber, bool force);

  uint16_t readProgramWord(const uint16_t *ptr) const;
  uint8_t makeAttr(Color foreground, Color background) const;
  uint16_t asciiToGlyph(char c) const;
  bool parseGlyphToken(const char *text, size_t index,
                       uint16_t &glyph, size_t &consumed) const;
  bool isHex(char c) const;
  uint8_t hexValue(char c) const;
  uint16_t cellIndex(const WindowState &window, uint8_t x, uint8_t y) const;
  bool inBounds(const WindowState &window, uint8_t x, uint8_t y) const;
};